version: '3.1'
services:
  stats-server:
    build: stat_service/stat_server
    image: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=stat
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: base_service
    image: base-service
    ports:
      - "8080:8080"
    depends_on:
      - base-db
    environment:
      - DB_NAME=base
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root


  ewm-db:
    image: postgres:14-alpine
    container_name: base-db
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_DB=base
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
